== Exercises

We have covered the basics of Elixir with which you can understand almost all lines of code generated by the `phx.new` command in Chapter 1.
Use the code generated in the first chapter to complete the following exercises.

1. List out the public and private functions defined in `mix.exs`.
2. What is the data type of the return value of each of the functions in `mix.exs`?
3. In the `mix.exs` file, what is the data type of the elements inside the tuple in `deps` function.
4. What is the arity of the `index` function in `PageController`?
5. Rewrite the `render` function call inside `PageController.index` using the pipe operator.
6. Identify all modules that use the `use` macro.
7. Identify all modules that use `use LearnPhoenixWeb` and replace the line with the injected code. Run `mix phx.server` to see that it still works as before.
8. List out all instances of pattern matching on function head.
9. Which module in the `learn_phoenix` app is responsible for starting the supervisor tree?
10. List out all instances of named and unnamed ignore operator.
