== Mix

In Chapter 1, we used the `mix` commands to create a new Phoenix project, download dependencies, run the server, etc. It is a command line tool that gets installed as part of the Elixir installation. Using `mix` you can create a new Elixir project or run any of the pre-built `mix` tasks.

In the Ruby world, the closest thing to `mix` is `rake` but unlike `rake`, `mix` is officially a part of the Elixir language and plays an important role in managing an Elixir project.

To see a list of `mix` tasks that you can execute on your machine, run the command `mix help` in your terminal.

This will list all tasks that are known to `mix`.

----
→ mix help
mix                   # Runs the default task (current: "mix run")
mix app.start         # Starts all registered apps
mix app.tree          # Prints the application tree
mix archive           # Lists installed archives
mix archive.build     # Archives this project into a .ez file
mix archive.install   # Installs an archive locally
mix archive.uninstall # Uninstalls archives
mix clean             # Deletes generated application files
mix cmd               # Executes the given command
mix compile           # Compiles source files
mix deps              # Lists dependencies and their status
mix deps.clean        # Deletes the given dependencies' files
mix deps.compile      # Compiles dependencies
mix deps.get          # Gets all out of date dependencies
mix deps.tree         # Prints the dependency tree
mix deps.unlock       # Unlocks the given dependencies
mix deps.update       # Updates the given dependencies
(... trimmed)
----

A `mix` task is basically a module with a function to perform the given task. For each of the task listed above, there is a module that the Elixir installation on our system is aware of. We can also teach `mix` to do new tasks that are project specific by writing a simple module within our project.

The following definition from Mix https://hexdocs.pm/mix/Mix.Task.html[documentation] explains how simple it is to create a new `mix` task.

****
A Mix task can be defined by simply using Mix.Task in a module starting with Mix.Tasks. and defining the `run/1` function.

The `run/1` function will receive a list of all arguments passed to the command line.
****

[source,elixir]
----
defmodule Mix.Tasks.Hello do
  use Mix.Task

  def run(_args) do
    Mix.shell.info "Hello World!"
  end
end
----

If we add the above code to our `learn_phoenix` project under `lib/tasks/hello.ex`, we can run the new task by `mix hello`.

----
→ mix hello
Hello World!
----
Our new task `hello` now prints the message "Hello World!" .

Library authors make extensive use of this feature. They extend `mix` giving us new commands like `phx.new`, `phx.server`, `ecto.migrate` etc. Basically the authors of Phoenix and Ecto have added `mix` tasks in their libraries which are available in any Elixir project that includes those libraries as dependencies.

If you are curious, you can look at the code for various `mix` tasks that are bundled with the Elixir language in https://github.com/elixir-lang/elixir/tree/master/lib/mix/lib/mix/tasks[this page]. The `mix` tasks that are available in projects depending on Phoenix are available https://github.com/phoenixframework/phoenix/tree/master/lib/mix/tasks[here] and those for Ecto library are at https://github.com/elixir-ecto/ecto/tree/master/lib/mix/tasks[here].

We will come across several `mix` tasks in the subsequent chapters. Remember that each time, we run `mix something`, `mix` is running a function which is defined in a file like those that we created above.

Finally before we end our quick tour on `mix` let's look at one of the `mix` commands that we will frequently use throughout this book. On our terminal, run `mix test`

----
~/pio/learn_phoenix
→ mix test
Compiling 1 file (.ex)
..

Finished in 0.05 seconds
2 tests, 0 failures

Randomized with seed 432540
----

When we run `mix test` all the test files under the `test` folder in our project are executed and the result of the tests are printed on screen.

In our new `learn_phoenix` project, we have a few test files generated by default. You can look at those under `test/learn_phoenix_web/*`.

Later in this book, as we use Test Driven Development (TDD) to develop an ecommerce site, `mix test` will become an integral part of our workflow.
